In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("../Data/Clean_data/df_final_demo_cleaned.csv")

In [3]:
data.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [4]:
data['tenure_years'].describe()

count    70595.000000
mean        12.052950
std          6.871819
min          2.000000
25%          6.000000
50%         11.000000
75%         16.000000
max         62.000000
Name: tenure_years, dtype: float64

In [5]:
data['age'].describe()

count    70594.000000
mean        46.442240
std         15.591273
min         13.500000
25%         32.500000
50%         47.000000
75%         59.000000
max         96.000000
Name: age, dtype: float64

In [6]:
age_vs_tenure = pd.crosstab(data['age'], data['tenure_years'])

In [7]:
age_vs_tenure

tenure_years,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,...,46.0,47.0,48.0,49.0,50.0,51.0,52.0,54.0,55.0,62.0
age,,,,,,,,,,,,,,,,,,,,,
13.5,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14.0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14.5,1,0,9,8,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15.0,0,4,6,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15.5,0,0,11,9,7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93.5,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
94.0,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95.5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
data[data['tenure_years'] >= data['age']]

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months
108,7449147,27.0,330.0,26.5,F,2.0,215247.66,3.0,6.0
846,4267612,28.0,345.0,28.0,F,2.0,32358.76,3.0,6.0
970,4955883,29.0,349.0,26.0,F,2.0,37122.69,2.0,5.0
1138,1330615,23.0,285.0,18.5,M,2.0,35553.33,3.0,6.0
1194,4286237,21.0,257.0,17.5,F,2.0,32577.78,5.0,8.0
...,...,...,...,...,...,...,...,...,...
70420,6911362,30.0,361.0,23.0,F,2.0,51142.87,3.0,3.0
70437,699213,23.0,286.0,17.0,M,2.0,29734.42,6.0,6.0
70439,6672629,24.0,299.0,23.0,U,4.0,91746.29,4.0,4.0
70479,9696505,20.0,250.0,18.5,F,2.0,15010.15,2.0,2.0
70524,9147180,31.0,374.0,24.0,F,2.0,57062.46,5.0,5.0

In [12]:
data_final = pd.read_csv("../Data/Clean_data/final_test_data.csv")

In [13]:
merged = pd.merge(data, data_final, on='client_id', how='inner')

In [14]:
merged.head()

,client_id,tenure_years,tenure_months,age,gender,num_accts,balance,calls_last_6_months,logons_last_6_months,visitor_id,visit_id,process_step,date_time,source,group_test
0,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0,427070339_1413275162,104438405_2368283624_817211,start,2017-03-29 10:58:35,pt1,test
1,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0,427070339_1413275162,104438405_2368283624_817211,start,2017-03-29 10:59:43,pt1,test
2,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0,427070339_1413275162,104438405_2368283624_817211,start,2017-03-29 11:01:40,pt1,test
3,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0,427070339_1413275162,104438405_2368283624_817211,start,2017-03-29 11:02:44,pt1,test
4,836976,6.0,73.0,60.5,U,2.0,45105.3,6.0,9.0,427070339_1413275162,228976764_46825473280_96584,start,2017-04-02 11:21:28,pt1,test

In [15]:
experiment = pd.read_csv("../Data/Clean_data/df_final_experiment_clients_cleaned.csv")

In [16]:
experiment.head()

   client_id group_test
0    9988021       test
1    8320017       test
2    4033851    control
3    1982004       test
4    9294070    control

In [17]:
experiment['group_test'].value_counts()

group_test
test       26968
control    23532
Name: count, dtype: int64

In [19]:
age_vs_group = pd.crosstab(merged['group_test'], merged['age'])

In [20]:
age_vs_group

age,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,...,91.0,91.5,92.0,92.5,93.0,93.5,94.0,94.5,95.5,96.0
group_test,,,,,,,,,,,,,,,,,,,,,
control,11,179,174,252,198,455,304,604,350,674,...,17,6,24,18,12,32,11,0,0,4
test,8,232,140,456,258,510,317,674,476,1003,...,22,19,15,10,15,0,13,5,6,6