# 01. Importing Libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd

# 02. Importing Data

In [3]:
data = pd.read_pickle("../Data/Clean_data/web_funnel_sorted.pkl")

In [4]:
test_data = pd.read_csv("../Data/Clean_data/df_final_experiment_clients_cleaned.csv")

In [5]:
data.head()

,client_id,visitor_id,visit_id,process_step,date_time,source
265216,9088444,242404224_96732670250,423038079_46067236368_400417,step_3,2017-03-15 00:03:03,pt1
134323,7179755,167765295_97487764427,264484508_5982901710_928530,start,2017-03-15 00:19:28,pt1
134324,7179755,167765295_97487764427,264484508_5982901710_928530,step_1,2017-03-15 00:20:50,pt1
134325,7179755,167765295_97487764427,264484508_5982901710_928530,step_2,2017-03-15 00:22:52,pt1
134326,7179755,167765295_97487764427,264484508_5982901710_928530,step_3,2017-03-15 00:23:47,pt1

In [6]:
test_data.head()

   client_id group_test
0    9988021       test
1    8320017       test
2    4033851    control
3    1982004       test
4    9294070    control

In [7]:
data.shape

(744641, 6)

In [8]:
test_data.shape

(70609, 2)

In [9]:
data.index

Index([265216, 134323, 134324, 134325, 134326, 134327, 501516, 501517, 501518,
       501519,
       ...
       450078, 450079, 557322, 557323, 557324, 212626, 212627, 212628, 710463,
       490849],
      dtype='int64', length=744641)

In [10]:
data.sort_index(inplace=True)

In [11]:
data.head()

,client_id,visitor_id,visit_id,process_step,date_time,source
0,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,pt1
1,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:23:09,pt1
2,9056452,306992881_89423906595,1000165_4190026492_760066,start,2017-06-04 01:07:29,pt2
3,9056452,306992881_89423906595,1000165_4190026492_760066,step_1,2017-06-04 01:07:32,pt2
4,9056452,306992881_89423906595,1000165_4190026492_760066,step_2,2017-06-04 01:07:56,pt2

In [12]:
final_test_data = pd.merge(data, test_data, on='client_id')

In [13]:
final_test_data

,client_id,visitor_id,visit_id,process_step,date_time,source,group_test
0,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17,pt1,test
1,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:23:09,pt1,test
2,7338123,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,pt1,test
3,7338123,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,pt1,test
4,7338123,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,pt1,test
...,...,...,...,...,...,...,...
443892,6627522,730634087_44272418812,999988789_76411676596_272843,step_1,2017-04-21 23:49:22,pt1,test
443893,6627522,730634087_44272418812,999988789_76411676596_272843,step_2,2017-04-21 23:50:16,pt1,test
443894,6627522,730634087_44272418812,999988789_76411676596_272843,step_1,2017-04-21 23:51:00,pt1,test
443895,6627522,730634087_44272418812,999988789_76411676596_272843,start,2017-04-21 23:51:09,pt1,test
443896,3761538,522028589_37033306085,999991142_15352368745_399725,start,2017-04-08 13:21:03,pt1,NaN

In [14]:
final_test_data.dtypes

client_id                int64
visitor_id              object
visit_id                object
process_step            object
date_time       datetime64[ns]
source                  object
group_test                 str
dtype: object

In [15]:
# exporting merged data to csv
final_test_data.to_csv("../Data/Clean_data/final_test_data.csv", index=False)

In [17]:
# exporting merged data to pkl
final_test_data.to_pickle("../Data/Clean_data/final_test_data.pkl")