## Import libraries

In [3]:
import pandas as pd
import numpy as np

## Importing data

In [4]:
df = pd.read_csv("./df_final_demo.txt")
fec = pd.read_csv("./df_final_experiment_clients.txt")
wd1 = pd.read_csv("./df_final_web_data_pt_1.txt")
wd2 = pd.read_csv("./df_final_web_data_pt_2.txt")

## Analysis

In [ ]:
df.head()
# id, age, number of accounts
# ternure is the length of time between a customer's first and last order dates, normalized to the period of time you are using.
# calls and log ons in last 6 months?

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [10]:
df.shape

(70609, 9)

In [8]:
df.nunique()

client_id           70609
clnt_tenure_yr         54
clnt_tenure_mnth      482
clnt_age              165
gendr                   4
num_accts               8
bal                 70333
calls_6_mnth            8
logons_6_mnth           9
dtype: int64

In [ ]:
df["gendr"].value_counts()
# u stands for unknown ????
# gendr needs to be converted to gender

gendr
U    24122
M    23724
F    22746
X        3
Name: count, dtype: int64

In [ ]:
df["calls_6_mnth"].value_counts()

# It makes sense that this column is calls in last 6 months.

calls_6_mnth
6.0    14112
1.0    11016
2.0    10252
3.0     8752
0.0     7732
4.0     7175
5.0     6627
7.0     4929
Name: count, dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  str
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 4.9 MB

In [5]:
fec.head()
# easy. just in which group they were. it would be the base of our database if we use SQL

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [15]:
fec.shape

(70609, 2)

Both groups navigated through an identical process sequence: an initial page, three subsequent steps, and finally, a confirmation page signaling process completion.

The goal is to see if the new design leads to a better user experience and higher process completion rates.

(this is from the student portal, I guess we could group by visit_id and see how long it took depending on the version, how many steps back did they make during the process and, obviously, how many completed the process.)

In [ ]:
wd1.head()
#it's the web data. 
#client_id is the common identifier among every dataset.
#each visit_id is a visit to the website.
#visitor_id is a unique identifier for each visitor.
#process_step is the step in the process
#together with the date and time, we can know when the visit happened and what they did in the website.

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [16]:
wd1.shape
# group by client_ids

(343141, 5)

In [7]:
wd2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [17]:
wd2.shape

(412264, 5)